services:
  telemetry:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    environment:
      ENABLE_LOGS_ALL: "true"
      OTEL_METRIC_EXPORT_INTERVAL: 1000
    healthcheck:
      test: test -e /tmp/ready
      interval: 5s
      timeout: 2s
      retries: 20
