ALTER TABLE forum.users
    ADD COLUMN IF NOT EXISTS deleted    BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

ALTER TABLE forum.forums
    ADD COLUMN IF NOT EXISTS deleted    BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

ALTER TABLE forum.threads
    ADD COLUMN IF NOT EXISTS deleted    BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

ALTER TABLE forum.posts
    ADD COLUMN IF NOT EXISTS deleted    BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;
