### LIST_FORUMS

GET {{API_URL}}/api/v1/forum HTTP/1.1
Accept: "application/json"
Content-Type: application/json


### 


### CREATE_THREAD

POST {{API_URL}}/api/v1/forum/85cf156c-5c30-49ba-9ba0-ea47f05ddcc4/thread HTTP/1.1
Accept: "application/json"
Content-Type: application/json

{
  "authorId": "79783d28-c42f-47a8-8efb-58876c3dec3d",
  "forumId": "85cf156c-5c30-49ba-9ba0-ea47f05ddcc4",
  "title": "Cyberpsycho sighted"
}


### 


### GET_THREAD

GET {{API_URL}}/api/v1/forum/85cf156c-5c30-49ba-9ba0-ea47f05ddcc4/thread/f5b5d836-7660-4d9d-88b1-86144476c4e8 HTTP/1.1
Accept: "application/json"
Content-Type: application/json


### 


### LIST_THREAD

GET {{API_URL}}/api/v1/forum/85cf156c-5c30-49ba-9ba0-ea47f05ddcc4/thread HTTP/1.1
Accept: "application/json"
Content-Type: application/json


### 


### PATCH_THREAD

PATCH {{API_URL}}/api/v1/forum/85cf156c-5c30-49ba-9ba0-ea47f05ddcc4/thread HTTP/1.1
Accept: "application/json"
Content-Type: application/json

{
  "id": "f5b5d836-7660-4d9d-88b1-86144476c4e8",
  "title": "Cyberpsycho sighted"
}


### 


### DELETE_THREAD

DELETE {{API_URL}}/api/v1/forum/85cf156c-5c30-49ba-9ba0-ea47f05ddcc4/thread/f5b5d836-7660-4d9d-88b1-86144476c4e8/delete HTTP/1.1
Accept: "application/json"
Content-Type: application/json


### 


### DELETE_THREAD

POST {{API_URL}}/api/v1/forum/85cf156c-5c30-49ba-9ba0-ea47f05ddcc4/thread/f5b5d836-7660-4d9d-88b1-86144476c4e8/restore HTTP/1.1
Accept: "application/json"
Content-Type: application/json


### 


### DELETE_THREAD

DELETE {{API_URL}}/api/v1/forum/85cf156c-5c30-49ba-9ba0-ea47f05ddcc4/thread/f5b5d836-7660-4d9d-88b1-86144476c4e8/purge HTTP/1.1
Accept: "application/json"
Content-Type: application/json
